Repository coffincw/UMass-STEM-Discord-Bot, pull requests merged in 2020-04, with the labels that each got.

#29 Added $lanify
  memes/arun/zoomarun.PNG
  memes/marius/zoommarius.png
  src/bot.py
  src/face_detection.py
Labels: enhancement

#32 Implement recursive meme commands
  README.md
  server-data/stem-discord-data.dat
  src/bot.py
  src/custom_meme.py
Labels: enhancement

#34 Alphabetize getlist and myroles and add special roles
  server-data/stem-discord-data.bak
  server-data/stem-discord-data.dat
  server-data/stem-discord-data.dir
  src/stem_role_commands.py
  src/stem_server_roles.py
Labels: adjustment, bug

#39 Setup Travis CI
  .travis.yml
  Procfile
  pytest.ini
  requirements.txt
  server-data/stem-discord-data.bak
  server-data/stem-discord-data.dat
  server-data/stem-discord-data.dir
  src/umassstembot/bot.py
  src/umassstembot/conftest.py
  src/umassstembot/coronavirus.py
  src/umassstembot/custom_meme.py
  src/umassstembot/face_detection.py
  src/umassstembot/filters.py
  src/umassstembot/overlay.py
  src/umassstembot/stem_role_commands.py
  src/umassstembot/stem_server_roles.py
  tests/meme_test/facedetection_test.py
  tests/meme_test/filters_test.py
  tests/meme_test/overlay_test.py
  tests/reference_images/facedetection/facedetection01.png
  tests/reference_images/facedetection/facedetection02.png
  tests/reference_images/filters/filters_customHighlight.png
  tests/reference_images/filters/filters_highlight.png
  tests/reference_images/filters/filters_intensify.png
  tests/reference_images/filters/filters_mirrorX.png
  tests/reference_images/filters/filters_mirrorY.png
  tests/reference_images/filters/filters_pixelate.png
  tests/reference_images/filters/filters_saturate.png
  tests/reference_images/overlay/overlay01.png
  tests/reference_images/overlay/overlay02.png
  tests/reference_images/overlay/overlay03.png
  tests/reference_images/overlay/overlay04.png
  tests/reference_images/overlay/overlay05.png
  tests/reference_images/overlay/overlay06.png
  tests/reference_images/overlay/overlay07.png
  tests/test_images/facedetection/facedetection01.png
  tests/test_images/facedetection/facedetection02.png
  tests/test_images/filters/filters_customHighlight.png
  tests/test_images/filters/filters_highlight.png
  tests/test_images/filters/filters_intensify.png
  tests/test_images/filters/filters_mirrorX.png
  tests/test_images/filters/filters_mirrorY.png
  tests/test_images/filters/filters_pixelate.png
  tests/test_images/filters/filters_saturate.png
  tests/test_images/overlay/overlay01.png
  tests/test_images/overlay/overlay02.png
  tests/test_images/overlay/overlay03.png
  tests/test_images/overlay/overlay04.png
  tests/test_images/overlay/overlay05.png
  tests/test_images/overlay/overlay06.png
  tests/test_images/overlay/overlay07.png
Labels: enhancement

#42 Small fix to mirror and add returns for errors
  server-data/stem-discord-data.dat
  src/umassstembot/bot.py
Labels: bug

#43 Add $stats command
  README.md
  src/umassstembot/bot.py
  src/umassstembot/stem_role_commands.py
Labels: enhancement

#45 Fix member count and add percentage to $stats
  README.md
  server-data/stem-discord-data.dat
  src/umassstembot/bot.py
  src/umassstembot/stem_role_commands.py
Labels: enhancement
